<?php
/**
 * AttributeFilterParameterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  \Loop54\API\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Loop54 Engine
 *
 * Loop54 Search is a learning search engine for e-commerce. It helps online shoppers find what they’re looking for, and allows them to explore a wider range of relevant products in a retailer’s catalogue.
 *
 * OpenAPI spec version: V3
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Loop54\API\OpenAPI;

/**
 * AttributeFilterParameterTest Class Doc Comment
 *
 * @category    Class
 * @description Used for filtering entities that have a certain attribute value.
 * @package     \Loop54\API\OpenAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AttributeFilterParameterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AttributeFilterParameter"
     */
    public function testAttributeFilterParameter()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "attribute_name"
     */
    public function testPropertyAttributeName()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "comparison_mode"
     */
    public function testPropertyComparisonMode()
    {
    }
}
