<?php
/**
 * SearchResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  \Loop54\API\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Loop54 Engine
 *
 * Loop54 Search is a learning search engine for e-commerce. It helps online shoppers find what they’re looking for, and allows them to explore a wider range of relevant products in a retailer’s catalogue.
 *
 * OpenAPI spec version: V3
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Loop54\API\OpenAPI;

/**
 * SearchResponseTest Class Doc Comment
 *
 * @category    Class
 * @description The result of a search operation.
 * @package     \Loop54\API\OpenAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SearchResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SearchResponse"
     */
    public function testSearchResponse()
    {
    }

    /**
     * Test attribute "makes_sense"
     */
    public function testPropertyMakesSense()
    {
    }

    /**
     * Test attribute "spelling_suggestions"
     */
    public function testPropertySpellingSuggestions()
    {
    }

    /**
     * Test attribute "related_queries"
     */
    public function testPropertyRelatedQueries()
    {
    }

    /**
     * Test attribute "results"
     */
    public function testPropertyResults()
    {
    }

    /**
     * Test attribute "related_results"
     */
    public function testPropertyRelatedResults()
    {
    }

    /**
     * Test attribute "custom_data"
     */
    public function testPropertyCustomData()
    {
    }
}
