<?php
namespace Loop54\API;

interface Request
{
    /**
     * Actually perform the request and get a result.
     *
     * @param OpenAPI\Api\UserInitiatedApi $instance
     *    An instance of the low-level autogenerated OpenAPI client.
     *
     * @param string $apiversion
     *    Currently supposed to be "V3".
     *
     * @param string $libversion
     *    A string identifying which library and which version used.
     *
     * @param string $apikey
     *    A string containing the API key to use for the request.
     *
     * @param string $userid
     *    A string identifying the remote end user, often an UUID.
     *
     * @param string $userip
     *    The IP from where the end user connection originates.
     *
     * @param string $useragent
     *    User-Agent of the browser the end user is operating.
     *
     * @param string $referer
     *    The Referer header from the end user.
     *
     * @return mixed
     */
    public function perform(
        $instance,
        $apiversion,
        $libversion,
        $apikey,
        $userid,
        $userip,
        $useragent,
        $referer
    );
}
