<?php
/**
 * UserInitiatedApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Loop54\API\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Loop54 Engine
 *
 * Loop54 Search is a learning search engine for e-commerce. It helps online shoppers find what they’re looking for, and allows them to explore a wider range of relevant products in a retailer’s catalogue.
 *
 * OpenAPI spec version: V3
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Loop54\API\OpenAPI;

use \Loop54\API\OpenAPI\Configuration;
use \Loop54\API\OpenAPI\ApiException;
use \Loop54\API\OpenAPI\ObjectSerializer;

/**
 * UserInitiatedApiTest Class Doc Comment
 *
 * @category Class
 * @package  Loop54\API\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserInitiatedApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for autoCompletePost
     *
     * Find autocompletions for a query.
     *
     */
    public function testAutoCompletePost()
    {
    }

    /**
     * Test case for createEventsPost
     *
     * Create behaviour events.
     *
     */
    public function testCreateEventsPost()
    {
    }

    /**
     * Test case for getBasketRecommendationsPost
     *
     * Get basket recommendations.
     *
     */
    public function testGetBasketRecommendationsPost()
    {
    }

    /**
     * Test case for getComplementaryEntitiesPost
     *
     * Get Complementary entities.
     *
     */
    public function testGetComplementaryEntitiesPost()
    {
    }

    /**
     * Test case for getEntitiesByAttributePost
     *
     * Get entities by indexed attribute.
     *
     */
    public function testGetEntitiesByAttributePost()
    {
    }

    /**
     * Test case for getEntitiesPost
     *
     * Get entities.
     *
     */
    public function testGetEntitiesPost()
    {
    }

    /**
     * Test case for getRelatedEntitiesPost
     *
     * Get related entities.
     *
     */
    public function testGetRelatedEntitiesPost()
    {
    }

    /**
     * Test case for searchPost
     *
     * Perform a search request.
     *
     */
    public function testSearchPost()
    {
    }
}
